[package]
name = "fmt-extra"
version = "0.0.2"
description = "Extra formaters not shipped in the standard library"
license = "AGPL-3.0"
authors = ["Cody P Schafer <dev@codyps.com>"]
repository = "https://github.com/jmesmon/rust-fmt-extra.git"
