[package]
name = "fmt-extra"
version = "0.0.3"
description = "Extra formaters not shipped in the standard library"
license = "Apache-2.0 OR MIT"
authors = ["Cody P Schafer <dev@codyps.com>"]
repository = "https://github.com/jmesmon/rust-fmt-extra.git"
